global using IDP.Core.Common.Exceptions;
global using IDP.Core.Common.Extensions;
global using IDP.Core.Common.Interfaces;
global using IDP.Core.Common.Model;
global using IDP.Core.Domain;
global using IDP.Core.Domain.AggregateRoots.Clients;
global using IDP.Core.Domain.AggregateRoots.Lookups;
global using IDP.Core.Domain.AggregateRoots.Roles;
global using IDP.Core.Domain.AggregateRoots.Tenants;
global using IDP.Core.Domain.AggregateRoots.Users;
global using IDP.Core.Domain.Base;
global using IDP.Core.Domain.ComplexTypes;
global using IDP.Core.Infrastructure;
global using IDP.Core.OAuth.Model;
global using IDP.Core.Security;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Options;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics.CodeAnalysis;
global using System.Reflection;
global using static IDP.Core.Domain.AggregateRoots.Clients.Client;
global using static IDP.Core.Domain.AggregateRoots.Clients.ClientGrantType;
