<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.9" />
    <PackageReference Include="NLog" Version="6.0.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Templates\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Admin.Core\Admin.Core.csproj" />
    <ProjectReference Include="..\IDP.Core\IDP.Core.csproj" />
    <ProjectReference Include="..\IDP.Foundation\IDP.Foundation.csproj" />
    <ProjectReference Include="..\IDP.Infrastructure\IDP.Infrastructure.csproj" />
    <ProjectReference Include="..\IDP.Projection\IDP.Projection.csproj" />
  </ItemGroup>

</Project>
