<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <PackageId>TokenIDP.Server</PackageId>
    <Title>TokenIDP Server</Title>
    <Description>TokenIDP server components and identity provider host package.</Description>
    <Authors>TokenIDP</Authors>
    <Company>TokenIDP</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <PackageTags>TokenIDP;oauth;openid-connect;identity-provider;iam;authentication;authorization;oauth2;oidc;jwt;dotnet;aspnetcore</PackageTags>
    <Copyright>Copyright (c) 2026 TokenIDP</Copyright>
    <PackageReadmeFile>README.NuGet.md</PackageReadmeFile>
    <PackageIcon>TokenIDP.png</PackageIcon>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
    <PackageReference Include="NLog" Version="6.1.3" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.NuGet.md" Pack="true" PackagePath="README.md" />
    <None Include="TokenIDP.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TokenIDP.Core\TokenIDP.Core.csproj" />
    <ProjectReference Include="..\TokenIDP.Infrastructure\TokenIDP.Infrastructure.csproj" />
    <ProjectReference Include="..\TokenIDP.Workers\TokenIDP.Workers.csproj" />
  </ItemGroup>

</Project>
