import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { renderPage } from "./lib.mjs";
import { pages } from "./pages.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const siteRoot = path.resolve(__dirname, "..");

const generatedArtifacts = [
  "index.html",
  "Landing.html",
  "contact.html",
  "contact",
  "docs",
  "blogs",
  "usecases",
  "Contact",
  "Docs",
  "Blogs",
  "UseCases",
];

for (const artifact of generatedArtifacts) {
  fs.rmSync(path.join(siteRoot, artifact), { recursive: true, force: true });
}

for (const page of pages) {
  const outputPath = path.join(siteRoot, page.outputPath);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const html =
    "<!-- Generated by site-src/build.mjs. Do not edit directly. -->\n" +
    renderPage(page);
  fs.writeFileSync(outputPath, html, "utf8");
}

console.log(`Generated ${pages.length} HTML pages in ${siteRoot}`);
