import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { renderPage } from "./lib.mjs";
import { pages } from "./pages.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const siteRoot = path.resolve(__dirname, "..");
const defaultDeployDir = "D:\\IIS Deployment\\IDPMarketing";

const generatedArtifacts = [
  "index.html",
  "Landing.html",
  "contact.html",
  "contact",
  "docs",
  "blogs",
  "usecases",
  "Contact",
  "Docs",
  "Blogs",
  "UseCases",
];

const staticArtifacts = ["assets", "Auth Code Flow.svg"];

function resolveDeployDir() {
  const cliArgs = process.argv.slice(2);
  const deployArgIndex = cliArgs.findIndex((arg) => arg === "--deployDir");
  const deployArgValue =
    deployArgIndex >= 0 ? cliArgs[deployArgIndex + 1] : undefined;
  const envValue = process.env.IDP_SUPPORTING_DOCS_DEPLOY_DIR;
  const deployDir = deployArgValue || envValue || defaultDeployDir;

  return path.resolve(deployDir);
}

function copyArtifact(sourceRoot, targetRoot, artifact) {
  const sourcePath = path.join(sourceRoot, artifact);

  if (!fs.existsSync(sourcePath)) {
    return;
  }

  const targetPath = path.join(targetRoot, artifact);
  fs.rmSync(targetPath, { recursive: true, force: true });
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.cpSync(sourcePath, targetPath, { recursive: true });
}

for (const artifact of generatedArtifacts) {
  fs.rmSync(path.join(siteRoot, artifact), { recursive: true, force: true });
}

for (const page of pages) {
  const outputPath = path.join(siteRoot, page.outputPath);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const html =
    "<!-- Generated by site-src/build.mjs. Do not edit directly. -->\n" +
    renderPage(page);
  fs.writeFileSync(outputPath, html, "utf8");
}

const deployDir = resolveDeployDir();
const artifactsToCopy = [...generatedArtifacts, ...staticArtifacts];

fs.mkdirSync(deployDir, { recursive: true });

for (const artifact of artifactsToCopy) {
  copyArtifact(siteRoot, deployDir, artifact);
}

console.log(`Generated ${pages.length} HTML pages in ${siteRoot}`);
console.log(`Copied site output to ${deployDir}`);
